version: '3'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8081
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  consumer:
    build: ./consumer
    volumes:
      - .:/app
      - /app/consumer/node_modules
    ports:
      - "3002:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    depends_on:
      - kafka
  producer:
    build: ./producer
    volumes:
      - .:/app
      - /app/producer/node_modules
    ports:
      - "3001:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    depends_on:
      - kafka
    # healthcheck:
    #   test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
